
[projects.dotbot]
repo = "DotBot-firmware" # if the project name is different from the repo name
build = "BUILD_TARGET=dotbot-v2 BUILD_CONFIG=Debug DOCKER_TARGETS=03app_dotbot make docker"
list-outputs = "ls -l projects/03app_dotbot/Output/dotbot-v2/Debug/Exe"

[projects.aiot_play_fw]
build = "BUILD_CONFIG=Debug make docker"

[projects.lakers]
setup = """
echo 'test lakers setup'
"""
build = "cargo build"
run = "cargo run --bin coapserver"
list-outputs = "ls -l target/debug"

[projects.Atlas]
build = '''
pip install -r requirements.txt
python RunSim.py
'''

[_swarmake]
openswarm-url = "https://github.com/openswarm-eu"
repositories = [
    "lakers",
    "happyserial",
    "Atlas",
    "aiot_play_fw",
    "aiot_gateway",
    "aiot_play_pcb",
    "microbit",
    "DotBot-firmware",
    "PyDotBot",
    "qrkey",
    "alvarado23lighthouse",
    "dotbot-authority",
    "DotBot-hardware",
    "draft-song-lake-ra",
    "draft-lopez-lake-edhoc-psk",
    "swarm-energy-replenishment",
    "minimal-length-swarm-networks",
    "multi-human-swarm-control",
    "Kasena",
    ".github",
    "dda",
    "aiot_play_fw_zephyr",
    "freebot-gatt-control",
    "freebot-example",
    "ARK-including-design-and-compilation",
    "ICRA2025_BatteryFreeRobot",
    "swarmit",
]
build-dir = "build"
