name: CI Workflow

on:
  push:
    branches: [main]
    tags: 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  testing-ci:
    name: Testing CI
    runs-on: ubuntu-latest

    steps:
      - name: just testing
        run: |
          echo just testing
