name: Main Action

on:
  push:
    branches: [main]
    tags: 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  install-swarmake:
    name: Install swarmake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install swarmake
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install swarmake package

      - name: Test swarmake
        run: |
          swarmake --version

  build-python-based:
    needs: install-swarmake
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [happyserial, swarmit, pydotbot, qrkey]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install swarmake package

      - name: Build ${{ matrix.target }}
        run: |
          BUILD_CONFIG=debug swarmake build ${{ matrix.target }}

  build-python-js-based:
    needs: install-swarmake
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [dotbot-authority] # TODO: move pydotbot to this workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install swarmake package

      - name: Build ${{ matrix.target }}
        run: |
          BUILD_CONFIG=debug swarmake build ${{ matrix.target }}

  build-rust-based:
    needs: install-swarmake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install swarmake package

      - name: Build freebot-gatt-control
        run: |
          BUILD_CONFIG=debug swarmake build freebot-gatt

  build-docker-based:
    needs: install-swarmake
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [dotbot, aiot_play_fw, human-swarm, dda]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install swarmake package

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build ${{ matrix.target }}
        run: |
          BUILD_CONFIG=debug swarmake build ${{ matrix.target }}
